
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;
import model.bean.Tributacao;
import model.dao.ColaboradorDAO;
import util.Util;
import model.dao.TributacaoDAO;



public class ViewTributacao extends javax.swing.JInternalFrame {

    
    
    public ViewTributacao() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) TabelaTributacao.getModel();
        TabelaTributacao.setRowSorter(new TableRowSorter(modelo));
        readTable();
              
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelAcao = new javax.swing.JPanel();
        btnincluir = new javax.swing.JButton();
        btnatualizar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        btnlimparcampos = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        PanelDados = new javax.swing.JPanel();
        lbldescricao = new javax.swing.JLabel();
        txtdescricao = new javax.swing.JTextField();
        lbluf = new javax.swing.JLabel();
        combouf = new javax.swing.JComboBox<>();
        lblaliquota = new javax.swing.JLabel();
        txtaliquota = new javax.swing.JFormattedTextField();
        lblredutor = new javax.swing.JLabel();
        txtredutor = new javax.swing.JFormattedTextField();
        lblsaidaentrada = new javax.swing.JLabel();
        comboentradasaida = new javax.swing.JComboBox<>();
        lblusuariocadastro = new javax.swing.JLabel();
        lblusuarioalteracao = new javax.swing.JLabel();
        txtusuariocadastro = new javax.swing.JFormattedTextField();
        txtusuarioalteracao = new javax.swing.JFormattedTextField();
        lbldtcadastro = new javax.swing.JLabel();
        lbldtalteracao = new javax.swing.JLabel();
        txtdtcadastro = new javax.swing.JFormattedTextField();
        txtdtalteracao = new javax.swing.JFormattedTextField();
        chkcancelado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaTributacao = new javax.swing.JTable();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("ENTERPRISE - CADASTRO DE TRIBUTOS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PainelAcao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnincluir.setBackground(new java.awt.Color(255, 153, 153));
        btnincluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-plus-16.png"))); // NOI18N
        btnincluir.setText("INCLUIR");
        btnincluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnincluir.setPreferredSize(new java.awt.Dimension(120, 25));
        btnincluir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnincluirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnincluirFocusLost(evt);
            }
        });
        btnincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincluirActionPerformed(evt);
            }
        });
        btnincluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnincluirKeyPressed(evt);
            }
        });

        btnatualizar.setBackground(new java.awt.Color(255, 153, 153));
        btnatualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnatualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-available-updates-16.png"))); // NOI18N
        btnatualizar.setText("ATUALIZAR");
        btnatualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnatualizar.setPreferredSize(new java.awt.Dimension(120, 25));
        btnatualizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnatualizarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnatualizarFocusLost(evt);
            }
        });
        btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarActionPerformed(evt);
            }
        });
        btnatualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnatualizarKeyPressed(evt);
            }
        });

        btncancelar.setBackground(new java.awt.Color(255, 153, 153));
        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancel-16.png"))); // NOI18N
        btncancelar.setText("CANCELAR");
        btncancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar.setPreferredSize(new java.awt.Dimension(120, 25));
        btncancelar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btncancelarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btncancelarFocusLost(evt);
            }
        });
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        btncancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btncancelarKeyPressed(evt);
            }
        });

        btnbuscar.setBackground(new java.awt.Color(255, 153, 153));
        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-search-16.png"))); // NOI18N
        btnbuscar.setText("BUSCAR");
        btnbuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbuscar.setPreferredSize(new java.awt.Dimension(120, 25));
        btnbuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnbuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnbuscarFocusLost(evt);
            }
        });
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        btnbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnbuscarKeyPressed(evt);
            }
        });

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });

        btnlimparcampos.setBackground(new java.awt.Color(255, 153, 153));
        btnlimparcampos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnlimparcampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-limpar-formatação-16.png"))); // NOI18N
        btnlimparcampos.setText("LIMPAR CAMPOS");
        btnlimparcampos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimparcampos.setPreferredSize(new java.awt.Dimension(120, 25));
        btnlimparcampos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnlimparcamposFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnlimparcamposFocusLost(evt);
            }
        });
        btnlimparcampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparcamposActionPerformed(evt);
            }
        });
        btnlimparcampos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnlimparcamposKeyPressed(evt);
            }
        });

        btnimprimir.setBackground(new java.awt.Color(255, 153, 153));
        btnimprimir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-print-16.png"))); // NOI18N
        btnimprimir.setText("IMPRIMIR");
        btnimprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnimprimir.setPreferredSize(new java.awt.Dimension(120, 25));
        btnimprimir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnimprimirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnimprimirFocusLost(evt);
            }
        });
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });
        btnimprimir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnimprimirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PainelAcaoLayout = new javax.swing.GroupLayout(PainelAcao);
        PainelAcao.setLayout(PainelAcaoLayout);
        PainelAcaoLayout.setHorizontalGroup(
            PainelAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAcaoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PainelAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnatualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnincluir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelAcaoLayout.createSequentialGroup()
                        .addGroup(PainelAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelAcaoLayout.createSequentialGroup()
                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnlimparcampos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        PainelAcaoLayout.setVerticalGroup(
            PainelAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAcaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelAcaoLayout.createSequentialGroup()
                        .addComponent(btnlimparcampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelAcaoLayout.createSequentialGroup()
                        .addComponent(btnincluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnatualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        PanelDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbldescricao.setText("DESCRIÇÃO DO TRIBUTO");

        txtdescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescricaoKeyPressed(evt);
            }
        });

        lbluf.setText("ESTADO (UF)");

        combouf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o estado", "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espirito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraiba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rodônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));
        combouf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboufFocusLost(evt);
            }
        });
        combouf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboufKeyPressed(evt);
            }
        });

        lblaliquota.setText("ALÍQUOTA");

        txtaliquota.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtaliquota.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtaliquota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaliquotaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaliquotaKeyTyped(evt);
            }
        });

        lblredutor.setText("REDUTOR");

        txtredutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtredutor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtredutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtredutorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtredutorKeyTyped(evt);
            }
        });

        lblsaidaentrada.setText("(E)NTRADA / (S)AIDA");

        comboentradasaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "ENTRADA", "SAIDA", " " }));
        comboentradasaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboentradasaidaFocusLost(evt);
            }
        });
        comboentradasaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboentradasaidaKeyPressed(evt);
            }
        });

        lblusuariocadastro.setText("Cadastrado por:");

        lblusuarioalteracao.setText("Alterado por....:");

        txtusuariocadastro.setEditable(false);
        try {
            txtusuariocadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("************************************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtusuariocadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuariocadastroActionPerformed(evt);
            }
        });

        txtusuarioalteracao.setEditable(false);
        try {
            txtusuarioalteracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*********************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbldtcadastro.setText("Data do Cadastro:");

        lbldtalteracao.setText("Data da Alteração:");

        try {
            MaskFormatter mascaraData = new MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter('_');
            txtdtcadastro.setEditable(false);
            try {
                txtdtcadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdtcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdtcadastroActionPerformed(evt);
            }
        });

        txtdtalteracao.setEditable(false);
        try {
            txtdtalteracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdtalteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdtalteracaoActionPerformed(evt);
            }
        });

        chkcancelado.setText("Registro Cancelado");
        chkcancelado.setEnabled(false);
        chkcancelado.setFocusable(false);

        javax.swing.GroupLayout PanelDadosLayout = new javax.swing.GroupLayout(PanelDados);
        PanelDados.setLayout(PanelDadosLayout);
        PanelDadosLayout.setHorizontalGroup(
            PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDadosLayout.createSequentialGroup()
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdescricao)
                            .addGroup(PanelDadosLayout.createSequentialGroup()
                                .addComponent(lbldescricao)
                                .addGap(0, 198, Short.MAX_VALUE)))
                        .addGap(2, 2, 2)
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combouf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbluf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblaliquota)
                            .addComponent(txtaliquota, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblredutor)
                            .addComponent(txtredutor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsaidaentrada)
                            .addComponent(comboentradasaida, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(PanelDadosLayout.createSequentialGroup()
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblusuarioalteracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblusuariocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusuariocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusuarioalteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbldtcadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldtalteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDadosLayout.createSequentialGroup()
                                .addComponent(txtdtalteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkcancelado))
                            .addComponent(txtdtcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelDadosLayout.setVerticalGroup(
            PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDadosLayout.createSequentialGroup()
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbluf)
                            .addComponent(lbldescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combouf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaliquota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelDadosLayout.createSequentialGroup()
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblredutor)
                            .addComponent(lblsaidaentrada)
                            .addComponent(lblaliquota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboentradasaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtredutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusuariocadastro)
                    .addComponent(txtusuariocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldtcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdtcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdtalteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldtalteracao)
                    .addComponent(lblusuarioalteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtusuarioalteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkcancelado))
                .addContainerGap())
        );

        TabelaTributacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TabelaTributacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "ESTADO (UF)", "ALIQUOTA (%)", "REDUTOR (%)", "(E)NTRADA / (S)AÍDA", "CADASTRADO POR", "DT CADASTRO", "ALTERADO POR", "DT ALTERAÇÃO", "CANCELADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaTributacao.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TabelaTributacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabelaTributacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaTributacaoMouseClicked(evt);
            }
        });
        TabelaTributacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaTributacaoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaTributacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(PainelAcao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(PanelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincluirActionPerformed
        incluir();
    }//GEN-LAST:event_btnincluirActionPerformed

    private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed
        atualizar();
    }//GEN-LAST:event_btnatualizarActionPerformed

    private void TabelaTributacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaTributacaoMouseClicked
        passagemderegistros();
    }//GEN-LAST:event_TabelaTributacaoMouseClicked

    private void TabelaTributacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaTributacaoKeyReleased
        passagemderegistros();
    }//GEN-LAST:event_TabelaTributacaoKeyReleased

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
         cancelar();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtdescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescricaoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if (txtdescricao.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "CAMPO DESCRICÃO É OBRIGATÓRIO !", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
                txtdescricao.requestFocus();

            }else{
                combouf.requestFocus();
            }
        }
    }//GEN-LAST:event_txtdescricaoKeyPressed

    private void txtaliquotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaliquotaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           txtredutor.requestFocus();
        } 
    }//GEN-LAST:event_txtaliquotaKeyPressed

    private void btnincluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnincluirKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            incluir();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnatualizar.requestFocus();
        } 
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnbuscar.requestFocus();
        }
    }//GEN-LAST:event_btnincluirKeyPressed

    private void txtaliquotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaliquotaKeyTyped
        String caracteres="0987654321,";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtaliquotaKeyTyped

    private void btnincluirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnincluirFocusGained
        btnincluir.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnincluirFocusGained

    private void btnincluirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnincluirFocusLost
         btnincluir.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_btnincluirFocusLost

    private void btnatualizarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnatualizarFocusGained
        btnatualizar.setBackground(Color.LIGHT_GRAY);        
    }//GEN-LAST:event_btnatualizarFocusGained

    private void btnatualizarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnatualizarFocusLost
        btnatualizar.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_btnatualizarFocusLost

    private void btncancelarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btncancelarFocusGained
        btncancelar.setBackground(Color.LIGHT_GRAY); 
    }//GEN-LAST:event_btncancelarFocusGained

    private void btncancelarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btncancelarFocusLost
        btncancelar.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_btncancelarFocusLost

    private void btnbuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnbuscarFocusGained
        btnbuscar.setBackground(Color.LIGHT_GRAY); 
    }//GEN-LAST:event_btnbuscarFocusGained

    private void btnbuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnbuscarFocusLost
        btnbuscar.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_btnbuscarFocusLost

    private void btnatualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnatualizarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btncancelar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnincluir.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            atualizar();
        }
    }//GEN-LAST:event_btnatualizarKeyPressed

    private void btncancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncancelarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnatualizar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnbuscar.requestFocus(); 
        }    
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cancelar();
        }  
    }//GEN-LAST:event_btncancelarKeyPressed

    private void btnbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnbuscarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btncancelar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnincluir.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            btnimprimir.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscar();
        }  
    }//GEN-LAST:event_btnbuscarKeyPressed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnbuscar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscar();
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void comboentradasaidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboentradasaidaFocusLost
        if (comboentradasaida.getSelectedItem().equals("Selecione o estado")){
            JOptionPane.showMessageDialog(null, "ESTADO (UF) INVÁLIDO !" , "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
            comboentradasaida.requestFocus();
        }
    }//GEN-LAST:event_comboentradasaidaFocusLost

    private void comboentradasaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboentradasaidaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnincluir.requestFocus();
        }
    }//GEN-LAST:event_comboentradasaidaKeyPressed

    private void comboufFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboufFocusLost
        if (combouf.getSelectedItem().equals("Selecione o estado")){
            JOptionPane.showMessageDialog(null, "ESTADO (UF) INVÁLIDO !" , "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
            combouf.requestFocus();
        }
    }//GEN-LAST:event_comboufFocusLost

    private void comboufKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboufKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtaliquota.requestFocus();
        }       
    }//GEN-LAST:event_comboufKeyPressed

    private void txtredutorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtredutorKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            comboentradasaida.requestFocus();
        }  
    }//GEN-LAST:event_txtredutorKeyPressed

    private void txtredutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtredutorKeyTyped
        String caracteres="0987654321,";
        if(!caracteres.contains(evt.getKeyChar()+"")){
           evt.consume();
        }
    }//GEN-LAST:event_txtredutorKeyTyped

    private void txtusuariocadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuariocadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuariocadastroActionPerformed

    private void txtdtcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdtcadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdtcadastroActionPerformed

    private void txtdtalteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdtalteracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdtalteracaoActionPerformed

    private void btnlimparcamposFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnlimparcamposFocusGained
        btnlimparcampos.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnlimparcamposFocusGained

    private void btnlimparcamposFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnlimparcamposFocusLost
        btnlimparcampos.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_btnlimparcamposFocusLost

    private void btnlimparcamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparcamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnlimparcamposActionPerformed

    private void btnlimparcamposKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnlimparcamposKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnincluir.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnimprimir.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            limparCampos();
        }
    }//GEN-LAST:event_btnlimparcamposKeyPressed

    private void btnimprimirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnimprimirFocusGained
        btnimprimir.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnimprimirFocusGained

    private void btnimprimirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnimprimirFocusLost
        btnimprimir.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_btnimprimirFocusLost

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        imprimir();
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void btnimprimirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnimprimirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            btnbuscar.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnlimparcampos.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            imprimir();
        }
    }//GEN-LAST:event_btnimprimirKeyPressed

    
    // **************************** Código Limpo  ******************************************
    
    public void setPosicao() {
          Dimension d = this.getDesktopPane().getSize();
          this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }   
    
    public void limparCampos() {
        txtdescricao.requestFocus();
        txtdescricao.setText("");
        combouf.setSelectedIndex(0);
        txtaliquota.setText("");
        txtredutor.setText("");
        comboentradasaida.setSelectedIndex(0);
        txtusuariocadastro.setText("");
        txtdtcadastro.setText("");
        txtusuarioalteracao.setText("");
        txtdtalteracao.setText("");
        chkcancelado.setSelected(false);
        txtbuscar.setText("");
    }

    public void readTable() {
        DefaultTableModel modelo  = (DefaultTableModel) TabelaTributacao.getModel();
        modelo.setNumRows(0);
        TributacaoDAO tributacaodao = new TributacaoDAO();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        for(Tributacao t: tributacaodao.read()){
            modelo.addRow(new Object[]{                
                t.getId_tributacao(),
                t.getDescricao(),
                t.getUf(),
                t.getAliquota(),
                t.getRedutor(),
                t.getEntradasaida(),
                t.getUsuariocadastro(),
                df.format(t.getDtcadastro()),
                t.getUsuarioalteracao(),
                df.format(t.getDtalteracao()),
                t.getCancelado()
            });
        }
        limparCampos();
    }
    
    public void readTableForDesc(String desc) {        
        DefaultTableModel modelo  = (DefaultTableModel) TabelaTributacao.getModel();
        modelo.setNumRows(0);
        TributacaoDAO tributacaodao = new TributacaoDAO();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        for(Tributacao t: tributacaodao.readForDesc(desc)){
            modelo.addRow(new Object[]{                
               t.getId_tributacao(),
                t.getDescricao(),
                t.getUf(),
                t.getAliquota(),
                t.getRedutor(),
                t.getEntradasaida(),
                t.getUsuariocadastro(),
                df.format(t.getDtcadastro()),
                t.getUsuarioalteracao(),
                df.format(t.getDtalteracao()),
                t.getCancelado()
            });
        }
        limparCampos();
    }
    
    public void incluir() {
        if (txtdescricao.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "CAMPO DESCRICÃO É OBRIGATÓRIO !", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
           txtdescricao.requestFocus();
        }
        if(combouf.getSelectedItem().equals("Selecione o estado")){
           JOptionPane.showMessageDialog(null, "CAMPO ESTADO (UF) É OBRIGATÓRIO !", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
           combouf.requestFocus(); 
        }
        if (comboentradasaida.getSelectedItem().equals("Selecione")){
           JOptionPane.showMessageDialog(null, "CAMPO ENTRADA OU SAIDA É OBRIGATÓRIO !", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
           comboentradasaida.requestFocus();
        } else {
            int resposta = JOptionPane.showConfirmDialog(null,"CONFIRMA A INCLUSÃO ?", "ENTERPRISE - DECISÃO", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                Tributacao    t             = new Tributacao();
                TributacaoDAO tributacaodao = new TributacaoDAO();
                Date dataSistema = new Date();
                t.setDescricao(txtdescricao.getText().toUpperCase());
                if (combouf.getSelectedItem().equals("Acre (AC)")){
                    t.setUf("AC");
                }
                if (combouf.getSelectedItem().equals("Alagoas (AL)")){
                    t.setUf("AL");
                }
                if (combouf.getSelectedItem().equals("Amapá (AP)")){
                    t.setUf("AP");
                }        
                if (combouf.getSelectedItem().equals("Amazonas (AM)")){
                    t.setUf("AM");
                }
                if (combouf.getSelectedItem().equals("Bahia (BA)")){
                    t.setUf("BA");
                }
                if (combouf.getSelectedItem().equals("Ceará (CE)")){
                    t.setUf("CE");
                }
                if (combouf.getSelectedItem().equals("Distrito Federal (DF)")){
                    t.setUf("DF");
                }  
                if (combouf.getSelectedItem().equals("Espirito Santo (ES)")){
                    t.setUf("ES");
                }  
                if (combouf.getSelectedItem().equals("Goiás (GO)")){
                    t.setUf("GO");
                }  
                if (combouf.getSelectedItem().equals("Maranhão (MA)")){
                    t.setUf("MA");
                }  
                if (combouf.getSelectedItem().equals("Mato Grosso (MT)")){
                    t.setUf("MT");
                }  
                if (combouf.getSelectedItem().equals("Mato Grosso do Sul (MS)")){
                   t.setUf("MS");
                }  
                if (combouf.getSelectedItem().equals("Minas Gerais (MG)")){
                   t.setUf("MG");
                }  
                if (combouf.getSelectedItem().equals("Pará (PA)")){
                   t.setUf("PA");
                }  
                if (combouf.getSelectedItem().equals("Paraiba (PB)")){
                    t.setUf("PB");
                }
                if (combouf.getSelectedItem().equals("Paraná (PR)")){
                    t.setUf("PR");
                }
                if (combouf.getSelectedItem().equals("Pernambuco (PE)")){
                    t.setUf("PE");
                }
                if (combouf.getSelectedItem().equals("Piauí (PI)")){
                    t.setUf("PI");
                } 
                if (combouf.getSelectedItem().equals("Rio de Janeiro (RJ)")){
                    t.setUf("RJ");
                }
                if (combouf.getSelectedItem().equals("Rio Grande do Norte (RN)")){
                    t.setUf("RN");
                }
                if (combouf.getSelectedItem().equals("Rio Grande do Sul (RS)")){
                    t.setUf("RS");
                }
                if (combouf.getSelectedItem().equals("Rodônia (RO)")){
                    t.setUf("RO");
                }
                if (combouf.getSelectedItem().equals("Roraima (RR)")){ 
                    t.setUf("RR");
                }
                if (combouf.getSelectedItem().equals("Santa Catarina (SC)")){ 
                    t.setUf("SC");
                }
                if (combouf.getSelectedItem().equals("São Paulo (SP)")){ 
                    t.setUf("SP");
                }
                if (combouf.getSelectedItem().equals("Sergipe (SE)")){ 
                    t.setUf("SE");
                }
                if (combouf.getSelectedItem().equals("Tocantins (TO)")){ 
                    t.setUf("TO");
                }
                t.setAliquota(Double.parseDouble(Util.formatarDecimalUs(txtaliquota.getText())));
                if (txtredutor.getText().isEmpty()){
                    txtredutor.setText("0");
                }
                t.setRedutor(Double.parseDouble(Util.formatarDecimalUs(txtredutor.getText())));
                if (comboentradasaida.getSelectedItem().equals("ENTRADA")){ 
                    t.setEntradasaida("E");
                }else{
                    t.setEntradasaida("S");
                }
                t.setUsuariocadastro(Integer.parseInt(ViewLogin.Id_Colaborador));
                t.setDtcadastro(Util.formatarDataPostgres(dataSistema));
                t.setUsuarioalteracao(Integer.parseInt(ViewLogin.Id_Colaborador));
                t.setDtalteracao(Util.formatarDataPostgres(dataSistema));
                t.setCancelado("N");
                //tributacaodao.create(t);
                 TributacaoDAO.getInstance().salvar(t);
            }
        } 
        readTable();
    }
    
    public void atualizar(){
        if (txtdescricao.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "CAMPO DESCRICÃO É OBRIGATÓRIO !", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
           txtdescricao.requestFocus();
        }
        if(combouf.getSelectedItem().equals("Selecione o estado")){
           JOptionPane.showMessageDialog(null, "CAMPO ESTADO (UF) É OBRIGATÓRIO !", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
           combouf.requestFocus(); 
        }
        if (comboentradasaida.getSelectedItem().equals("Selecione")){
           JOptionPane.showMessageDialog(null, "CAMPO ENTRADA OU SAIDA É OBRIGATÓRIO !", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
           comboentradasaida.requestFocus();
        } else {
            if (TabelaTributacao.getSelectedRow() != -1 ) {
                Tributacao     t = new Tributacao();
                TributacaoDAO tributacaodao = new TributacaoDAO();
                Date dataSistema = new Date();
                t.setId_tributacao((int)TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(),0));
                t.setDescricao(txtdescricao.getText().toUpperCase());
                if (combouf.getSelectedItem().equals("Acre (AC)")){
                    t.setUf("AC");
                }
                if (combouf.getSelectedItem().equals("Alagoas (AL)")){
                    t.setUf("AL");
                }
                if (combouf.getSelectedItem().equals("Amapá (AP)")){
                    t.setUf("AP");
                }        
                if (combouf.getSelectedItem().equals("Amazonas (AM)")){
                    t.setUf("AM");
                }
                if (combouf.getSelectedItem().equals("Bahia (BA)")){
                    t.setUf("BA");
                }
                if (combouf.getSelectedItem().equals("Ceará (CE)")){
                    t.setUf("CE");
                }
                if (combouf.getSelectedItem().equals("Distrito Federal (DF)")){
                    t.setUf("DF");
                }  
                if (combouf.getSelectedItem().equals("Espirito Santo (ES)")){
                    t.setUf("ES");
                }  
                if (combouf.getSelectedItem().equals("Goiás (GO)")){
                    t.setUf("GO");
                }  
                if (combouf.getSelectedItem().equals("Maranhão (MA)")){
                    t.setUf("MA");
                }  
                if (combouf.getSelectedItem().equals("Mato Grosso (MT)")){
                    t.setUf("MT");
                }  
                if (combouf.getSelectedItem().equals("Mato Grosso do Sul (MS)")){
                   t.setUf("MS");
                }  
                if (combouf.getSelectedItem().equals("Minas Gerais (MG)")){
                   t.setUf("MG");
                }  
                if (combouf.getSelectedItem().equals("Pará (PA)")){
                   t.setUf("PA");
                }  
                if (combouf.getSelectedItem().equals("Paraiba (PB)")){
                    t.setUf("PB");
                }
                if (combouf.getSelectedItem().equals("Paraná (PR)")){
                    t.setUf("PR");
                }
                if (combouf.getSelectedItem().equals("Pernambuco (PE)")){
                    t.setUf("PE");
                }
                if (combouf.getSelectedItem().equals("Piauí (PI)")){
                    t.setUf("PI");
                } 
                if (combouf.getSelectedItem().equals("Rio de Janeiro (RJ)")){
                    t.setUf("RJ");
                }
                if (combouf.getSelectedItem().equals("Rio Grande do Norte (RN)")){
                    t.setUf("RN");
                }
                if (combouf.getSelectedItem().equals("Rio Grande do Sul (RS)")){
                    t.setUf("RS");
                }
                if (combouf.getSelectedItem().equals("Rodônia (RO)")){
                    t.setUf("RO");
                }
                if (combouf.getSelectedItem().equals("Roraima (RR)")){ 
                    t.setUf("RR");
                }
                if (combouf.getSelectedItem().equals("Santa Catarina (SC)")){ 
                    t.setUf("SC");
                }
                if (combouf.getSelectedItem().equals("São Paulo (SP)")){ 
                    t.setUf("SP");
                }
                if (combouf.getSelectedItem().equals("Sergipe (SE)")){ 
                    t.setUf("SE");
                }
                if (combouf.getSelectedItem().equals("Tocantins (TO)")){ 
                    t.setUf("TO");
                }
                t.setAliquota(Double.parseDouble(Util.formatarDecimalUs(txtaliquota.getText())));
                t.setRedutor(Double.parseDouble(Util.formatarDecimalUs(txtredutor.getText())));
                if (comboentradasaida.getSelectedItem().equals("ENTRADA")){ 
                    t.setEntradasaida("E");
                } else {
                    t.setEntradasaida("S");
                }
                t.setUsuarioalteracao(Integer.parseInt(ViewLogin.Id_Colaborador));
                t.setDtalteracao(Util.formatarDataPostgres(dataSistema));
                // tributacaodao.update(t);
                TributacaoDAO.getInstance().salvar(t);
            } else {
                JOptionPane.showMessageDialog(null, "SELECIONE UMA OPÇÃO PARA ATUALIZAR", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
                txtdescricao.requestFocus();
            }
        }
        readTable();
    }
    
//    public void excluir(){
//        if (TabelaTributacao.getSelectedRow() != -1 ) {
//             Tributacao     t = new Tributacao();
//             TributacaoDAO tributacaodao = new TributacaoDAO();
//             t.setId_tributacao((int)TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(),0));
//             int resposta = JOptionPane.showConfirmDialog(null,"CONFIRMA A EXCLUSÃO ?", "ENTERPRISE - DECISÃO", JOptionPane.YES_NO_OPTION);
//             if (resposta == JOptionPane.YES_OPTION) {
//                 tributacaodao.delete(t);
//                 readTable();
//             }
//        } else {
//             JOptionPane.showMessageDialog(null, "SELECIONE UMA OPÇÃO PARA EXCLUIR", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
//             txtdescricao.requestFocus();
//        }
//    }
    
     public void cancelar() {   // ESTE MÉTODO CANCELA O REGISTRO 
        if (TabelaTributacao.getSelectedRow() != -1) {
            Date dataSistema = new Date();
            Tributacao t = new Tributacao();
            TributacaoDAO tributacaodao = new TributacaoDAO();
            if (chkcancelado.isSelected()) {
                int resposta = JOptionPane.showConfirmDialog(null, "ESTE REGISTRO ESTÁ CANCELADO DESEJA RETIRAR O CANCELAMENTO ?", "ENTERPRISE - DECISÃO", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) {
                    t.setCancelado("N");
                    t.setId_tributacao((int)TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(),0));
                    t.setUsuarioalteracao(Integer.parseInt(ViewLogin.Id_Colaborador));
                    t.setDtalteracao(Util.formatarDataPostgres(dataSistema));
                    chkcancelado.setSelected(false);
                    //tributacaodao.cancelar(t);
                    TributacaoDAO.getInstance().cancelar(t);
                }
           } else {
                int resposta = JOptionPane.showConfirmDialog(null, "DESEJA CANCELAR ESTE REGISTRO ?", "ENTERPRISE - DECISÃO", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) {
                   t.setCancelado("S");
                   t.setId_tributacao((int)TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(),0));
                   t.setUsuarioalteracao(Integer.parseInt(ViewLogin.Id_Colaborador));
                   t.setDtalteracao(Util.formatarDataPostgres(dataSistema));
                   chkcancelado.setSelected(true);
                   //tributacaodao.cancelar(t);
                  TributacaoDAO.getInstance().cancelar(t);
                }
           }
    } else {
           JOptionPane.showMessageDialog(null, "SELECIONE UM REGISTRO PARA CANCELAR !", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
           txtdescricao.requestFocus();
    }
       readTable();
    }
    
    
    public void buscar(){
        if (txtbuscar.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "INFORME A(S) LETRA(S) DA PALAVRA", "ENTERPRISE - ATENÇÃO", JOptionPane.ERROR_MESSAGE);
            txtbuscar.requestFocus();
            readTable();
        }else{
            readTableForDesc(txtbuscar.getText().toUpperCase());
        }
    }
            
    public void imprimir(){
        TributacaoDAO tributacaodao = new TributacaoDAO();
        tributacaodao.imprimir();
        limparCampos();
    }
    public void passagemderegistros(){ //Metodo para a passagem de Registros 
         if (TabelaTributacao.getSelectedRow()!= -1){
            ColaboradorDAO colaboradordao = new ColaboradorDAO(); 
            txtdescricao.setText(TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 1).toString());
            
            //**********************************************************************************************
             
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("AC"))  {
               combouf.setSelectedIndex(1);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("AL"))  {
               combouf.setSelectedIndex(2);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("AP"))  {
               combouf.setSelectedIndex(3);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("AM"))  {
               combouf.setSelectedIndex(4);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("BA"))  {
               combouf.setSelectedIndex(5);
            }  
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("CE"))  {
               combouf.setSelectedIndex(6);
            }  
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("DF"))  {
               combouf.setSelectedIndex(7);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("ES"))  {
               combouf.setSelectedIndex(8);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("GO"))  {
               combouf.setSelectedIndex(9);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("MA"))  {
               combouf.setSelectedIndex(10);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("MT"))  {
               combouf.setSelectedIndex(11);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("MS"))  {
               combouf.setSelectedIndex(12);
            } 
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("MG"))  {
               combouf.setSelectedIndex(13);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("PA"))  {
               combouf.setSelectedIndex(14);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("PB"))  {
               combouf.setSelectedIndex(15);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("PR"))  {
               combouf.setSelectedIndex(16);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("PE"))  {
               combouf.setSelectedIndex(17);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("PI"))  {
               combouf.setSelectedIndex(18);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("RJ"))  {
               combouf.setSelectedIndex(19);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("RN"))  {
               combouf.setSelectedIndex(20);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("RS"))  {
               combouf.setSelectedIndex(21);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("RO"))  {
               combouf.setSelectedIndex(22);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("RR"))  {
               combouf.setSelectedIndex(23);
            } 
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("SC"))  {
               combouf.setSelectedIndex(24);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("SP"))  {
               combouf.setSelectedIndex(25);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("SE"))  {
               combouf.setSelectedIndex(26);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 2).toString().equals("TO"))  {
               combouf.setSelectedIndex(27);
            }
            //***********************************************************************************************
            txtaliquota.setText(TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 3).toString());
            txtredutor.setText(TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 4).toString());
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 5).toString().equals("E"))  {
               comboentradasaida.setSelectedIndex(1);
            } else {
               comboentradasaida.setSelectedIndex(2);
            }
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 6).toString().equals("0")) {
                txtusuariocadastro.setText("ADMINISTRADOR");
            } else {
                txtusuariocadastro.setText(colaboradordao.pesquisaId_Colaborador(TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 6).toString()));
            }
            txtdtcadastro.setText(TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 7).toString());
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 8).toString().equals("0")) {
                txtusuarioalteracao.setText("ADMINISTRADOR");
            } else {
                txtusuarioalteracao.setText(colaboradordao.pesquisaId_Colaborador(TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 8).toString()));
            }
            txtdtalteracao.setText(TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 9).toString());
            if (TabelaTributacao.getValueAt(TabelaTributacao.getSelectedRow(), 10).toString().equals("S")) {
                chkcancelado.setSelected(true);
            } else {
                chkcancelado.setSelected(false);
            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelAcao;
    private javax.swing.JPanel PanelDados;
    private javax.swing.JTable TabelaTributacao;
    private javax.swing.JButton btnatualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnincluir;
    private javax.swing.JButton btnlimparcampos;
    private javax.swing.JCheckBox chkcancelado;
    private javax.swing.JComboBox<String> comboentradasaida;
    private javax.swing.JComboBox<String> combouf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblaliquota;
    private javax.swing.JLabel lbldescricao;
    private javax.swing.JLabel lbldtalteracao;
    private javax.swing.JLabel lbldtcadastro;
    private javax.swing.JLabel lblredutor;
    private javax.swing.JLabel lblsaidaentrada;
    private javax.swing.JLabel lbluf;
    private javax.swing.JLabel lblusuarioalteracao;
    private javax.swing.JLabel lblusuariocadastro;
    private javax.swing.JFormattedTextField txtaliquota;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JFormattedTextField txtdtalteracao;
    private javax.swing.JFormattedTextField txtdtcadastro;
    private javax.swing.JFormattedTextField txtredutor;
    private javax.swing.JFormattedTextField txtusuarioalteracao;
    private javax.swing.JFormattedTextField txtusuariocadastro;
    // End of variables declaration//GEN-END:variables
}
